### ISSUE TITLE
Will it work with esata ?

### ISSUE THREAD

**Issue by master8282** [cilix-lab/ubuntu-wrt#4]
Hello,
I suppose you made custom u-boot img.
Does it have drivers for esata ? Can I use esata ssd instead regular flash drive?

**Comment by cilix-lab** [comment]
Hi! Sorry I haven't replied sooner, but I honestly missed the notification on this issue.  

There's no custom u-boot image, actually. You can see how things developed for McDebian and UbuntuWRT on the original [McDebian thread] (https://www.snbforums.com/threads/linksys-wrt1900ac-wrt1900acs-wrt1200ac-and-wrt3200acm-router-debian-implementation.28394/).  

I think everything needed for esata should be there, but I can't assure you it will work and don't have any esata to test it, sorry!  

If you do try it, let me know if it worked. If it doesn't, I'll look into the kernel config.
