### ISSUE TITLE
new mwlwifi driver

### ISSUE THREAD

**Issue by tienhuynh5312** [cilix-lab/ubuntu-wrt#5]
Hi,
can you update new build for mwlwifi driver to newer build. I am having prolems with wifi performance. Or how can I update it?
Best,
Tien Huynh

**Comment by cilix-lab** [comment]
At commit [728c803](https://github.com/cilix-lab/ubuntu-wrt/commit/728c803d353a3eedd50e3d8b8100cc22268d8b64), mwlwifi was updated to current commit.  

If you're on UbuntuWRT 18.01-beta, you can update the kernel by doing: `apt-get update && apt-get install linux-image`, considering you kept UbuntuWRT repository in apt sources. After installing `linux-image`, you must reboot.  

If you wish to build the whole thing, just `git clone` the linux kernel, `git clone` this repository to the same folder where you cloned linux kernel, and run `./update` script to pull everything else you'll need. When it finishes, it'll ask you if you want to `./merge` to `linux-stable`, answer `y` (yes) and it will copy everything needed to build the kernel.  

Then, `cd` to `linux-stable` folder and build the kernel:  
```
# Build the kernel
export ARCH=arm
export CROSS_COMPILE=arm-none-eabi-
make modules
make zImage
make dtbs

# Merge DTB into zImage
cp arch/arm/boot/zImage zImage; cat arch/arm/boot/dts/armada-385-linksys-rango.dtb >> zImage

# Make u-boot image
mkimage -A arm -O linux -T kernel -C none -a 0x200000 -e 0x200000 -n "linux" -d zImage uImage
```

And that `uImage` is what you want to flash to your router, but don't forget you have to install the firmware and modules to the rootfs first:  
```
# Install modules
make ARCH=arm CROSS_COMPILE=arm-none-eabi- INSTALL_MOD_PATH=<path-to-your-rootfs> modules_install

# Install firmware
mkdir -p <path-to-your-rootfs>/lib/firmware/mwlwifi <path-to-your-rootfs>/lib/firmware/mrvl
cp <path-to-sources-folder>/mwlwifi/bin/firmware/* <path-to-your-rootfs>/lib/firmware/mwlwifi/
cp <path-to-sources-folder>/linux-firmware/mrvl/sd8887_uapsta.bin <path-to-your-rootfs>/lib/firmware/mrvl/
```
Where `<path-to-sources-folder>` is where you `git clone`d the repo.  

Hope it helps. Building the kernel is a quite complex procedure that you might want to skip by upgrading from the repository. You can always check the original thread on McDebian which contains a lot of info about creating your own rootfs, building the kernel, etc.
