### ISSUE TITLE
Revert back to Linksys firmware only by hardware on-off mechanism

### ISSUE THREAD

**Issue by tienhuynh5312** [cilix-lab/ubuntu-wrt#7]
As you know, WRT series has two firmware partitions, and we can switch back and forth between them by turning on-off 3 times. However, can we somehow disable that "count" if we remotely execute reboot command from terminal? It prevents automatic reverting back to Linksys partition every 3 boots, and I have to turn on-off 3 times again to be back Ubuntuwrt partition.
I used DAVID502 on LEDE build and I noticed that he somehow managed to do that, but wonder there is a way to do on ubuntuWRT

**Comment by ValCher1961** [comment]
Sorry, it seems it is controlled by U-boot.

**Comment by tienhuynh5312** [comment]
@ValCher1961 I think the same way. davidc502 build can do it, and I dont know why we cannot do it here.

**Comment by ValCher1961** [comment]
@tienhuynh5312 
In U-boot there is env - 'auto_recovery', if its value is - 'yes', then the count of cycles of inclusions works, and if - 'no', the counter is turned off and loading will be executed always from the current partition.

**Comment by cilix-lab** [comment]
New update out depending on USB thumb for booting the kernel, so you can keep your original firmware in the flash. Won't be able to switch from factory to UbuntuWRT by turn-on-off, though.
